# Generated by Django 4.0.4 on 2022-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueKeys', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'devBlog',
            },
        ),
    ]
