# Generated by Django 4.0.4 on 2023-01-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_stripedb_delete_usersnear'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeServiceDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
                ('userId', models.CharField(default='', max_length=100)),
                ('serviceName', models.CharField(default='', max_length=200)),
                ('amount', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'StripeServiceDb',
            },
        ),
        migrations.RenameField(
            model_name='stripedb',
            old_name='userId',
            new_name='accountId',
        ),
        migrations.RemoveField(
            model_name='stripedb',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='stripedb',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stripedb',
            name='serviceName',
        ),
        migrations.AlterField(
            model_name='stripedb',
            name='email',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
