# Generated by Django 4.0.4 on 2023-01-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stripeservicedb_rename_userid_stripedb_accountid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeservicedb',
            old_name='userId',
            new_name='accountId',
        ),
    ]
